[build]
  publish = "build/web"
  command = """
    git clone --depth 1 https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:$(pwd)/flutter/bin"
    flutter doctor -v
    flutter pub get
    flutter build web --release
  """
  publish = "build/web"